[build]
  publish = "web"
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
[[headers]]
  for = "/*.mnote"
  [headers.values]
    Content-Type = "application/x-mnote+zip"
